### ISSUE TITLE
Missing checkbox in the OCR settings

### ISSUE THREAD

**Issue by irene-wilson** [Nuix/Nx#1]
Hello,
I've just run all the examples and I have noticed that the OCR settings displays 5 labels for only 4 boxes ("Update PDF Text" - "Update Item Text" - "Regenerate PDFs" - "Deskew" - "Update Duplicates").
Kind regards,
Irène

**Comment by JuicyDragon** [comment]
Hello Irene,

Thank you for pointing that out.  I believe I have determined what the issue is an how to fix it.  As I add functionality for newer versions of Nuix, I try to also keep things compatible with older versions of Nuix.  In the case of the [OcrSettings control](https://github.com/Nuix/Nx/blob/v1.6.1/Java/src/main/java/com/nuix/nx/controls/OcrSettings.java#L487-L492), if the version of Nuix is detected to be before 7.2.x then the control hides the associated checkbox, but it looks like I forgot to also hide the label.

### Current Code
```java
// Update duplicates was added in Nuix 7.2.0
if(NuixConnection.getCurrentNuixVersion().isLessThan("7.2.0")){
	chckbxUpdateDuplicates.setVisible(false);
	lblTimeoutminutes.setVisible(false);
	timeoutMinutes.setVisible(false);
}
```

## Should Be
```java
// Update duplicates was added in Nuix 7.2.0
if(NuixConnection.getCurrentNuixVersion().isLessThan("7.2.0")){
	lblUpdateDuplicates.setVisible(false);
	chckbxUpdateDuplicates.setVisible(false);
	lblTimeoutminutes.setVisible(false);
	timeoutMinutes.setVisible(false);
}
```

I'm going to make the change, test and make a new release shortly.  Thanks!
